eecs280staff/tutorials

- Gemfile.lock
- README.md
1. Updated Gemfile.lock as instructed in README
2. Fixed README directory from "eecs281-setup" to "tutorials"
Note: this is a very minor pr meant as git/github practice for future contributions to the project.
> README directory change

- Gemfile.lock
- docs/setup_eecs281.md
This commit adds instructions for using `getopt` to the eecs281 setup tutorial. Specifically, this commit does the following:
- Adds instructions for including `getopt` for Visual Studio.
- Provides access to `getopt.c` and `getopt.h` via a Google Drive link.
- Provides the boilerplate `getopt` code for students to use in all eecs281 projects.
Ideally, I'd like to remove Google Drive links, and allow students to access the files through a GitHub repository, but I'm still waiting for access to the EECS281 github repos.
> Add getopt setup instructions for VS + boilerplate getopt code

- docs/setup_xcode.md
Add a few subheadings to the Xcode tutorial so that we can more easily link to subsections from a Project Setup.
> Add Xcode headings

- docs/setup_visualstudio.md
- docs/setup_vscode.md
- docs/setup_xcode.md
Remove stale reference to src subdirectory.  Make the starter files download subsections consistent among the 3 IDEs.
> Bugfix old reference to src subdir

- docs/debugging_guide.md
- docs/setup_emacs.md
- docs/setup_gdb.md
- docs/setup_git.md
- docs/setup_lldb.md
- docs/setup_make.md
We've had some discussion about removing `setup.md` (#53 and #54) since it is largely unnecessary.
I took at look at what this would require and found that many of the links back to `setup.md` (or equivalently, `setup.html`) were actually *already broken*, because a significant amount had been moved into the individual IDE tutorials (e.g. links back to `setup.html#create-a-folder` were going to a section that no longer exists). Making the main setup tutorial more lightweight is a good change, but a few straggler links to the old beefy one persisted.
A number of tutorials also finished with a section that instructed students to "return to the main setup tutorial". Some of these were broken because of recent changes, but I think all are best removed anyway since it's a maintenance burden to …
> Fix Broken Dependencies and Remove setup.md

- .github/workflows/spec_preview.yml
I recently released [v1.9.0 of Primer Spec](https://github.com/eecs485staff/primer-spec/releases/tag/v1.9.0%2Bwn23) along with changes to [seshrs/build-primer-spec-action](https://github.com/seshrs/build-primer-spec-action). One of the new features is that Primer Spec will automatically generate a PDF version of every page in your website!
Unfortunately, we need to make a small change to the "spec previews" workflow to make the PR preview websites use the correct PDF URL.
I'll be making this change to all websites using [seshrs/upload-to-primer-spec-preview](https://github.com/seshrs/upload-to-primer-spec-preview).
Visit any Primer Spec page in the [spec preview website for this PR](https://preview.sesh.rs/previews/eecs280staff/tutorials/55/). Click the "Download" button in the Topbar. …
> [Primer Spec] Fix PDF URL in Spec Previews

- docs/setup_git.md
Add a callout to the top of the Git tutorial that helps students skip the install instructions.
This came up while I was working on https://github.com/eecs280staff/p2-cv/pull/186
> Add a quick start style callout

- docs/cli.md
It looks like a fresh WSL / Ubuntu install will have a `.bashrc`, not `.bash_profile`.
EDIT: I just modified this PR to create .bash_profile.  Simple.
> bash_profile -> bashrc

- docs/xgetopt.h
Fixes to `xgetopt.h` to support Visual Studio 2017.  This supports the EECS 281 tutorial `getopt` library for EECS 281 students.  Contribution from Dave Paoletti.
> Visual Studio 2017 compile fixes

- docs/cli.md
Based on Piazza post [@432](https://piazza.com/class/lbnv6k5pd0y6bz/post/432).
From [this link](https://wslutiliti.es/wslu/install.html#ubuntu), it appears some versions of Ubuntu require a different way of installing wslu (for wslview). The added commands are also taken from the link.
Unfortunately I do not have a Windows machine so am unable to test this, but it seemed to have worked for the student who posted on Piazza.
> Update wslu install pitfalls

- docs/setup_vscode.md
Use the simpler version of input redirection for the Code LLDB extension on macOS.
Check if this works on a mac with CodeLLDB and EECS 280 Project 1 main.exe with input redirection.
> Simplify CodeLLDB input redirection

- docs/setup_git.md
There was a stale development link in the Git tutorial.
> Fix a link error

- docs/setup_git.md
Changes made:
1. Clarify for students that their public key is in the file ending in .pub
2. Add warning to never share your private code
3. Clarify that SSH is passwordless so you won't see a prompt
4. Clarify that MacOS pitfall for key caching is only for the token
> Minor Changes to Git Tutorial for Clarification

- docs/setup_git.md
Add text and sample CLI output to clarify that students should see prompts after running the ssh-keygen command and that they should accept the default path (first prompt) and set up a passphrase (second and third prompts).
> Add prompts from ssh-keygen

- docs/setup_eecs281.md
Update the EECS 281 tutorial to remind student to compile with `make debug`.
Closes #89
> EECS 281 Tutorial compile with debug symbols

- docs/index.html
- docs/setup_vscode.md
When installing VS Code on macOS, it's easy to miss installing the Microsoft C/C++ extension, which is needed for intellisense.  Improve the workflow by indicating this extension install in *both* the macOS and Windows subsections instead of above both sections.
> VSCode on macOS avoid pitfall

- docs/cli.md
Potential confusion point found in Piazza: https://piazza.com/class/llcrbmqbuti3lq/post/139
This PR addresses this confusion and also makes the zsh section consistent with the bash section (which already contained a line with touch).
> Add "touch ~/.zshrc" for zsh customization

- docs/cli.md
Add a warning to the CLI tutorial that the `rm` command removes files forever.  Also correct an inconsistency to use `rm -rf`.
Thanks to @amirkamil for the suggestion.
> Add a warning near the rm command

- docs/setup_emacs.md
- docs/setup_git.md
- docs/setup_visualstudio.md
- docs/setup_vscode.md
- docs/setup_xcode.md
Move the "Restart" section to the end of each IDE tutorial.  Same for the Git tutorial.
Closes #146
> Move restart section to the end

- docs/setup_caen.md
CAEN Linux SSH connections from off campus now require the VPN.  I was informed of this via email from CAEN.  It appears that some students are going to them for help.  Please consider this to be somewhat urgent.
> CAEN Linux Requires VPN

- docs/setup_vscode_wsl.md
Add a pitfall to the VSCode / WSL tutorial in the input redirection subsection.  Make sure students are using the right extension.
Closes #171 
See new pitfall [here](https://preview.sesh.rs/previews/eecs280staff/tutorials/172/setup_vscode_wsl.html#input-redirection)
> Add pitfall VSCode WSL / Input redirection

- docs/setup_wsl.md
This PR fixes #168 by instructing students to only uninstall Ubuntu.
The uninstall and install commands recommended in the Microsoft resources are unlikely to change, so they are directly encoded into the tutorial (rather than a link to an external page - there also isn't an external page I could find that concisely shows the uninstall + install together).
**Verification**
I worked through this process on a spare Windows machine.
1. Start with no WSL installed at all.
2. Install with `wsl --install` from administrator PowerShell.
3. Restart computer as prompted.
4. Open Ubuntu terminal. It prompts to create a user account. Close the terminal without doing that 😈.
5. Open Ubuntu terminal. `whoami` yields `root`.
6. Open PowerShell as administrator. `wsl --unregister Ubuntu`. (Side note, I …
> Reinstall only Ubuntu

- docs/index.html
Closes #167 and also adds CLI setup to Quick Start, so it's clearer to students to get command line tools/install WSL, etc. Only changing the main tutorial page, not any of the tutorial material. Resulting tutorial page looks like the below:
> add CLI setup to Quick Start and adds new column to Setup Tutorial for CLI

- docs/setup_asan.md
Adds a warning to run `make clean` after enabling sanitizers in Makefile to the Sanitizers tutorial
> Suggest `make clean` in Sanitizers tutorial

- docs/setup_wsl.md
The pitfall that instructs students to reinstall Ubuntu if they accidentally skip creating a root account has some redundant steps. I had intended to remove these when replacing with the easier reinstall method in #169 but must have missed doing it.
> Remove Redundant Steps in WSL Reinstall

- docs/setup_style.md
This PR updates the style checking tutorial for OCLint 22.02.
The changes are minor, since the main changes are updates to the `make style` target provided with individual projects. The `-no-analytics` option is no longer used, and the output includes the new version number.
Also fixes an existing typo in the example.
> Update to OCLint 22.02

- docs/setup_wsl.md
I ran into a student who got the usage message no matter what when they tried a `wsl` command from powershell. Even `wsl --version`. Some searching online suggested the fix added in this PR, which is to manually enable WSL in windows features, and that ended up solving the problem. I didn't think you had to do this anymore, but maybe this student had done something to specifically disable it.
> Add Troubleshooting Item for Infinite Help Message

- docs/setup_emacs.md
- docs/setup_gdb.md
- docs/setup_lldb.md
- docs/setup_visualstudio.md
- docs/setup_vscode_macos.md
- docs/setup_vscode_wsl.md
- docs/setup_xcode.md
We're releasing a revised P1 this term. This PR makes a few updates to the tutorial to match.
**P1 Starter Files**
The tutorials show output from `tree` and include several screenshots of various IDEs that happen to show some files. I updated the `tree` output since that was easy and it's nice to have that match. Instead of updating many images (which aren't necessarily focused on the exact starter files), I added a note that "your specific starter files might not match the image" where appropriate.
**Command Line Args instead of Input Redirection**
P1 now uses command line arguments instead of input redirection. So, I moved the command line arguments section before the input redirection section. I also switched the messages at the top of each, so that students are told to skip input …
> Update for Revised P1

- docs/setup_wsl.md
In #186, I made a commit to simplify the command from `wsl --install -d Ubuntu-24.04` to `wsl --install Ubuntu-24.04`.
I shouldn't have done that :). It turns out that on Windows 10 or outdated versions of the `wsl` command itself, the `-d` is required. See the note at the bottom of the `wsl --install` section here: https://learn.microsoft.com/en-us/windows/wsl/basic-commands#install
This PR adds back the `-d`.
> Use -d in wsl install command

- docs/setup_wsl.md
There are a few places we missed adding the 24.04.
The most significant is in the instructions for uninstalling and reinstalling (if they accidentally skipped creating a user account).
> Update output and instructions to match 24.04

- docs/setup_macos.md
- docs/setup_vscode_macos.md
Many students on Mac have been running into issues with their compiler. Reinstalling the XCode command-line tools seems to fix the issue.
In some cases, the standard library is no longer available and `#includes` stop working.
In other cases, students are getting a message like `xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools)`.
This PR adds a troubleshooting section with instructions for removing and reinstalling.
> Add Instructions for Reinstalling Compiler on Mac

- docs/setup_caen.md
- docs/setup_emacs.md
- docs/setup_style.md
https://caen.engin.umich.edu/connect/linux-login-service/
> Update CAEN Linux Remote Login Service URL

- docs/setup_macos.md
- docs/setup_vscode_macos.md
macOS tutorials refer to the home directory as the "Ubuntu home directory," this changes those references to just "home directory"
I'm assuming this is an artifact from copying from the WSL tutorials
> Remove WSL terminology from macOS tutorials
