eecs280staff/tutorials

docs/setup_vscode.md
Be explicit about changes to launch.json for Linux users
=> Linux launch.json

docs/style_guide.md
Fix the heading levels in the Style Guide to be consistent with the other tutorials.
=> Style Guide Nits

docs/setup_macos.md, docs/setup_visualstudio.md, docs/setup_vscode.md, docs/setup_wsl.md, docs/setup_xcode.md
Improve the linkage from the OS and IDE tutorials into the CLI tutorial.
=> CLI linkage

docs/cli.md
Noticed that the videos did not have the color inversion class for dark mode, so added those in.
=> Add color inversion to videos

docs/setup_visualstudio.md, docs/setup_vscode.md, docs/setup_xcode.md
The IDE tutorials use EECS 280 P1 starter files as an example of adding existing files to a project.  I got a very reasonable student email asking about these mysterious files.  Add a note about it.
=> Add a note about the EECS 280 P1 starter files

docs/setup_wsl.md
=> Add apt update

docs/setup_wsl.md
=> Add pitfalls to solve problems from office hours

docs/setup_vscode.md
Found some more opportunities to link to the CLI tutorial.  This was based on student troubles in office hours.
=> Link to CLI tutorial explanations

docs/setup_caen.md
Add timeout to SSH multiplexing configuration.  Also fix long file path problem in the SSH multiplexing configuration.
Closes #65 
Closes #66
=> SSH multiplexing timeout

docs/setup_vscode.md
=> Do not install MS cpptools extension pack

docs/cli.md, docs/setup_wsl.md
=> Added note on using Ubuntu instead of PowerShell

docs/setup_wsl.md
=> Fix absolute paths

docs/setup_vscode.md
=> Extra sanity checks on vscode_setup prereqs

docs/setup_wsl.md
Closes #98 
Preceded by (rejected) PR #99
=> Add Microsoft link for upgrading WSL 1 to 2

docs/setup_git.md
I forgot to check double-check for references to 485 when I reviewed #111 .  This PR fixing a tiny change I forgot.
=> Remove reference to 485

docs/setup_xcode.md
=> Check freopen for success

docs/setup_emacs.md
Make sure install is consistent with docs.
=> Update emacs use-package install

docs/setup_git.md
=> Fix two broken links in the GitHub tutorial

.github/workflows/spec_preview.yml
=> Don't generate pdfs by default

docs/setup_vscode.md
Suggested updates to the VS Code setup tutorial after running through it on my own machine.
=> Minor MacOS updates for current version of VS Code. Add some clarifications.

docs/setup_vscode_wsl.md
This PR fixes #150 and fixes #151.
=> Miscellaneous VS Code on Windows Fixes

docs/setup_caen.md
Working on #159 reminded me that this tutorial hasn't seen an update in a long time.  I freshened it up, shortening some stuff and adding reminders about the UM VPN.
Q: Do you think we should add screenshots of how to confirm you're on the VPN?
=> CAEN linux overhaul

docs/setup_visualstudio.md, docs/setup_xcode.md
=> Fix Typo: D in IDE stands for development, not debugging

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md
=> Fix issue template markdown formatting

docs/setup_vscode_macos.md
Add a troubleshooting subsection to fix #177
=> Troubleshooting CodeLLDB incompatible debug server

docs/setup_wsl.md
=> Specify Ubuntu version in WSL install instructions

docs/cli.md, docs/setup_caen.md, docs/setup_eecs281.md, docs/setup_emacs.md, docs/setup_git.md, docs/setup_lldb.md, docs/setup_macos.md, docs/setup_style.md, docs/setup_visualstudio.md, docs/setup_vscode_macos.md, docs/setup_vscode_wsl.md, docs/setup_wsl.md, docs/setup_xcode.md, docs/style_guide.md
This PR follows https://github.com/eecs280staff/stats/pull/380. The tutorial needs to use the new name `stats` rather than `p1-stats`.
=> Rename p1-stats to stats

docs/setup_vscode_wsl.md, docs/setup_wsl.md
This PR makes a few minor edits based on a run through the tutorial prior to the start of Fall 2025.
=> F25 Windows Test Run Edits
